---
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: sean
  labels:
    app.kubernetes.io/name: sean
    app.kubernetes.io/version: 9.0.0
    app.kubernetes.io/instance: sean
    app.kubernetes.io/managed-by: ArgoCD
spec:
  etcVolumeStorageConfig:
    storageClassName: kube-rook
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: kube-rook
    storageCapacity: 100Gi
  serviceTemplate:
    apiVersion: v1
    kind: Service
    spec:
      ports:
      - name: https
        port: 443
        protocol: TCP
        targetPort: 8088