---
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: simple-splunk
  labels:
    app.kubernetes.io/name: simple-splunk
    app.kubernetes.io/version: 9.0.0
    app.kubernetes.io/instance: simple-splunk
    app.kubernetes.io/managed-by: ArgoCD
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: 3
  resources:
    requests:
      memory: "12Gi"
      cpu: "8"
  etcVolumeStorageConfig:
    storageClassName: kube-rook
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: kube-rook
    storageCapacity: 100Gi
  serviceTemplate:
    apiVersion: v1
    kind: Service
    spec:
      ports:
      - name: https
        port: 443
        protocol: TCP
        targetPort: 8088