---
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: simple-splunk
  labels:
    app.kubernetes.io/name: simple-splunk
    app.kubernetes.io/version: 9.0.0
    app.kubernetes.io/instance: simple-splunk
    app.kubernetes.io/managed-by: ArgoCD
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  serviceTemplate:
    apiVersion: v1
    kind: Service
    metadata:
      name: splunk-simple-splunk-standalone-service
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: https
      labels:
        app.kubernetes.io/component: standalone
        app.kubernetes.io/instance: splunk-simple-splunk-standalone
        app.kubernetes.io/managed-by: splunk-operator
        app.kubernetes.io/name: standalone
        app.kubernetes.io/part-of: splunk-simple-splunk-standalone
    spec:
      ports:
      - name: http-web
        port: 9000
        protocol: TCP
        targetPort: 8000
      - name: http-hec
        port: 9088
        protocol: TCP
        targetPort: 8088
#      - name: https-spd
#        port: 8089
#        protocol: TCP
#        targetPort: 8089
#      - name: tcp
#        port: 9997
#        protocol: TCP
#        targetPort: 9997